// user constants
export const USER_RESET = "USER_RESET"

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"

export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST"
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS"
export const USER_AUTH_FAILURE = "USER_AUTH_FAILURE"

export const USER_LOGOUT = "USER_LOGOUT"

// app constants
export const APP_RESET = 'APP_RESET'
export const APP_SET_LOADING = "APP_SET_LOADING"
export const APP_ERROR_SHOW = 'APP_ERROR_SHOW'
export const APP_ERROR_HIDE = 'APP_ERROR_HIDE'
export const APP_NOTIF_SHOW = 'APP_NOTIF_SHOW'
export const APP_NOTIF_HIDE = 'APP_NOTIF_HIDE'
